DROP TABLE IF EXISTS projects;
DROP TABLE IF EXISTS parentOrgs;

CREATE TABLE parentOrgs (
  id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  name VARCHAR (256) UNIQUE NOT NULL,
  logo VARCHAR (1024)
);

CREATE TABLE projects (
  id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY, 
  lfxProjectId VARCHAR (128) UNIQUE NOT NULL, 
  name VARCHAR (512) UNIQUE NOT NULL, 
  industry VARCHAR (512)[], 
  description VARCHAR (4096) DEFAULT '',
  skills VARCHAR (128)[], 
  programYear INTEGER NOT NULL, 
  programTerm VARCHAR (128) NOT NULL,
  repository VARCHAR (256) NOT NULL,
  website VARCHAR (256) NOT NULL,
  amountRaised FLOAT NOT NULL DEFAULT 0,
  organizationId INTEGER NOT NULL, 
  CONSTRAINT fk_organizationId
    FOREIGN KEY (organizationId) 
	  REFERENCES parentOrgs(id)
    ON DELETE CASCADE
);
